### ISSUE TITLE
Update .travis.yml

### ISSUE THREAD

**Issue by mr-wellick** [mr-wellick/stock-market#42]
Need to update scripts in this file after migrating to create-react-app

```yml
script:
  - yarn run validate
after_success:
  - yarn run test:coverage

```
